[package]
name = "commander-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spinners-rs = '2.3.0'
commander = '0.1'
owo-colors = "3"
inquire = '0.6'
